---

- hosts: all

  connection: local
  user: '{{ ansible_ssh_user }}'
  gather_facts: 'no'

  tasks:
    - name: validate connection from rtr-1
      ios_ping:
        dest: '{{ item }}'
        state: 'present'
      when: "'rtr-1' in inventory_hostname"
      with_items:
        - '10.0.12.2'
        - '10.0.13.3'

    - name: validate connection from rtr-2
      ios_ping:
        dest: '{{ item }}'
        state: 'present'
      when: "'rtr-2' in inventory_hostname"
      with_items:
        - '10.0.12.1'
        - '10.0.24.4'
        - '10.0.23.3'

    - name: validate connection from rtr-3
      ios_ping:
        dest: '{{ item }}'
        state: 'present'
      when: "'rtr-3' in inventory_hostname"
      with_items:
        - '10.0.13.1'
        - '10.0.34.4'
        - '10.0.23.2'

    - name: validate connection from rtr-4
      ios_ping:
        dest: '{{ item }}'
        state: 'present'
      when: "'rtr-4' in inventory_hostname"
      with_items:
        - '10.0.24.2'
        - '10.0.34.3'

    - name: validate bgp connection from rtr-1
      ios_ping:
        dest: '{{ item }}'
        state: 'present'
      when: "'rtr-1' in inventory_hostname"
      with_items:
        - '10.0.0.4'

    - name: validate bgp connection from rtr-4
      ios_ping:
        dest: '{{ item }}'
        state: 'present'
      when: "'rtr-4' in inventory_hostname"
      with_items:
        - '10.0.0.1'
