---

hostname: rtr-4
domain_name: cisco.com

loopback:
  address: 10.0.0.4
  mask: 255.255.255.255

interfaces:
  0/2:
    alias: connection rtr-2
    address: 10.0.24.4
    mask: 255.255.255.0

  0/3:
    alias: connection rtr-3
    address: 10.0.34.4
    mask: 255.255.255.0

bgp:
  asn: 65002
  neighbor:
    - {address: 10.0.24.2, remote_as: 65000}
    - {address: 10.0.34.3, remote_as: 65000}
  networks:
    - {network: 10.0.24.0, mask: 255.255.255.0}
    - {network: 10.0.34.0, mask: 255.255.255.0}
    - {network: 10.0.0.4, mask: 255.255.255.255}
  maxpath: 2
