---

hostname: rtr-3
domain_name: cisco.com

loopback:
  address: 10.0.0.3
  mask: 255.255.255.255

interfaces:
  2:
    alias: connection rtr-3
    address: 10.0.23.3
    mask: 255.255.255.0

  3:
    alias: connection rtr-1
    address: 10.0.13.3
    mask: 255.255.255.0

  4:
    alias: connection rtr-4
    address: 10.0.34.3
    mask: 255.255.255.0

bgp:
  asn: 65000
  neighbor:
    - {address: 10.0.13.1, remote_as: 65001}
    - {address: 10.0.34.4, remote_as: 65002}
  networks:
    - {network: 10.0.23.0, mask: 255.255.255.0}
    - {network: 10.0.13.0, mask: 255.255.255.0}
    - {network: 10.0.34.0, mask: 255.255.255.0}
    - {network: 10.0.0.3, mask: 255.255.255.255}
  maxpath: 2
